version: '3.8'

services:
  pastevault:
    image: lonleysailor/pastevault:latest
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - DATABASE_PATH=/app/data/pastevault.db
      - ENVIRONMENT=production
      - JWT_SECRET=your-production-jwt-secret-here
      - REFRESH_JWT_SECRET=your-production-refresh-jwt-secret-here
    volumes:
      - pastevault_data:/app/data
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/api/health" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  pastevault_data:
    driver: local
